// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8I_qZ7fLgb-eooiMv7hBUMM_mQaFX4s',
    appId: '1:70112855680:web:db83403b8f95ffb1074865',
    messagingSenderId: '70112855680',
    projectId: 'bartersync',
    authDomain: 'bartersync.firebaseapp.com',
    storageBucket: 'bartersync.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQD0OULGLvlbsy9LFyArouQNuoT1efdk',
    appId: '1:70112855680:android:1486c625f573f250074865',
    messagingSenderId: '70112855680',
    projectId: 'bartersync',
    storageBucket: 'bartersync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbmPKInSdTD7vaRo-LyCH6ZktY_NVYeY',
    appId: '1:70112855680:ios:437616d9fd08cf59074865',
    messagingSenderId: '70112855680',
    projectId: 'bartersync',
    storageBucket: 'bartersync.appspot.com',
    iosBundleId: 'com.example.tradesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbmPKInSdTD7vaRo-LyCH6ZktY_NVYeY',
    appId: '1:70112855680:ios:259e8bce4825af0b074865',
    messagingSenderId: '70112855680',
    projectId: 'bartersync',
    storageBucket: 'bartersync.appspot.com',
    iosBundleId: 'com.example.tradesync.RunnerTests',
  );
}
